# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('amount', models.IntegerField(default=0)),
                ('expires', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=45)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=45)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=45)),
                ('zip', models.CharField(blank=True, max_length=45)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('chapter', models.IntegerField(default=4)),
                ('subscribejobs', models.IntegerField(default=0)),
                ('membership_expiry', models.DateField(null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('activation', models.TextField(blank=True, max_length=255)),
                ('pwdresetkey', models.TextField(blank=True, max_length=255)),
                ('remember_token', models.TextField(blank=True, max_length=255)),
                ('listserv', models.IntegerField(default=0)),
                ('featured', models.IntegerField(default=0)),
                ('accept_internal_messages', models.IntegerField(default=1)),
                ('notify_internal_messages', models.IntegerField(default=1)),
                ('public', models.IntegerField(default=1)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country')),
                ('membership_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.MembershipLevel')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PaymentMethod')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
